<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

class BranchController extends BaseController
{
    protected $model_name = 'Branch';



    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

}
